name: todo_list_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.13.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.3
  path: ^1.8.2
  google_fonts: ^4.0.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutterfire_cli: ^0.2.7
  validatorless: ^1.2.3
  cupertino_icons: ^1.0.2
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^5.4.3
  date_picker_timeline: ^1.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ToDoListIcons
      fonts:
        - asset: assets/fonts/ToDoListIcons.ttf
